[versions]
agp = "8.13.1"
kotlin = "2.2.21"
ksp = "2.3.3"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
composeVersion = "1.9.5"
encryptedPreferences = "1.3.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.0"
composeBom = "2025.11.01"
compose-compiler = "1.5.8"
landscapistGlide = "2.6.1"
loggingInterceptor = "5.3.2"
mockitoKotlin = "2.2.0"
navVersion = "2.9.6"
lottie = "6.7.1"
shimmer = "1.3.3"
okhttp = "5.3.2"
roomVersion = "2.8.4"
testJunitExt = "1.1.5"
kotlinxCoroutinesTest = "1.10.2"
mockitoCore = "5.20.0"
mockitoInline = "5.2.0"
navigationRuntimeKtx = "2.9.6"
testOrchestrator = "1.6.1"
roomKtx = "2.8.4"
testRules = "1.7.0"
testRunner = "1.5.2"
testTruth = "1.7.0"
googleTestTruth = "1.4.5"
espressoVersion = "3.5.1"
hiltVersion = "2.57.2"
retrofitVersion = "3.0.0"
androidMaterial = "1.13.0"
androidConstraintLayoutCompose = "1.1.1"
androidxTestCore = "1.7.0"
coreTesting = "2.2.0"
jacocoVersion = "0.8.11"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoVersion" }
androidx-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "coreTesting" }
androidx-core = { module = "androidx.test:core", version.ref = "androidxTestCore" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "testJunitExt" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navVersion" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomVersion" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomVersion" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "roomVersion" }

androidx-compose-material = { group = "androidx.compose.material", name = "material", version.ref = "composeVersion" }
androidx-navigation-runtime-ktx = { module = "androidx.navigation:navigation-runtime-ktx", version.ref = "navigationRuntimeKtx" }
androidx-test-orchestrator = { module = "androidx.test:orchestrator", version.ref = "testOrchestrator" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomKtx" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "testRules" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "testRunner" }
androidx-test-truth = { module = "androidx.test.ext:truth", version.ref = "testTruth" }
androidx-ui-test = { module = "androidx.compose.ui:ui-test", version.ref = "composeVersion" }
androidx-ui = { module = "androidx.compose.ui:ui", version.ref = "composeVersion" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "composeVersion" }
androidx-ui-test-junit4-android = { module = "androidx.compose.ui:ui-test-junit4-android", version.ref = "composeVersion" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "composeVersion" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofitVersion" }
converter-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "retrofitVersion" }
encrypted-preferences = { module = "com.pddstudio:encrypted-preferences", version.ref = "encryptedPreferences" }
google-android-material = { module = "com.google.android.material:material", version.ref = "androidMaterial" }
androidx-constraintlayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "androidConstraintLayoutCompose" }

dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltVersion" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "hiltVersion" }
dagger-hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltVersion" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
landscapist-glide = { module = "com.github.skydoves:landscapist-glide", version.ref = "landscapistGlide" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockitoInline" }
google-test-truth = { module = "com.google.truth:truth", version.ref = "googleTestTruth" }
mockito-kotlin = { module = "com.nhaarman.mockitokotlin2:mockito-kotlin", version.ref = "mockitoKotlin" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofitVersion" }
lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie" }
shimmer-compose = { group = "com.valentinilk.shimmer", name = "compose-shimmer", version.ref = "shimmer" }
test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoVersion" }
test-espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "espressoVersion" }
test-espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "espressoVersion" }
test-espresso-accessibility = { module = "androidx.test.espresso:espresso-accessibility", version.ref = "espressoVersion" }
test-idling-concurrent = { module = "androidx.test.espresso.idling:idling-concurrent", version.ref = "espressoVersion" }
jacoco-core = { group = "org.jacoco", name = "org.jacoco.core", version.ref = "jacocoVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hiltVersion" }
jacoco = { id = "jacoco" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
